from django.urls import path

from . import views


urlpatterns = [
    path(
        "wizard/",
        views.SingleStepWizardViewSet.as_view(),
        name="single-step-wizard",
    ),
    path(
        "wizard/<uuid:run_id>/",
        views.SingleStepWizardViewSet.as_view(),
        name="single-step-wizard-run",
    ),
    path(
        "wizard-without-done/",
        views.SingleStepWizardWithoutDoneViewSet.as_view(),
        name="single-step-wizard-without-done",
    ),
    path(
        "wizard-without-done/<uuid:run_id>/",
        views.SingleStepWizardWithoutDoneViewSet.as_view(),
        name="single-step-wizard-without-done-run",
    ),
    path(
        "wizard-done-data/",
        views.SingleStepWizardDoneDataViewSet.as_view(),
        name="single-step-wizard-done-data",
    ),
    path(
        "wizard-done-data/<uuid:run_id>/",
        views.SingleStepWizardDoneDataViewSet.as_view(),
        name="single-step-wizard-done-data-run",
    ),
    path(
        "wizard-done-run-data/",
        views.SingleStepWizardDoneRunDataViewSet.as_view(),
        name="single-step-wizard-done-run-data",
    ),
    path(
        "wizard-done-run-data/<uuid:run_id>/",
        views.SingleStepWizardDoneRunDataViewSet.as_view(),
        name="single-step-wizard-done-run-data-run",
    ),
    path(
        "linear-wizard/",
        views.LinearWizardViewSet.as_view(),
        name="linear-wizard",
    ),
    path(
        "linear-wizard/<uuid:run_id>/",
        views.LinearWizardViewSet.as_view(),
        name="linear-wizard-run",
    ),
    path(
        "done-linear-wizard/",
        views.DoneLinearWizardViewSet.as_view(),
        name="done-linear-wizard",
    ),
    path(
        "done-linear-wizard/<uuid:run_id>/",
        views.DoneLinearWizardViewSet.as_view(),
        name="done-linear-wizard-run",
    ),
    path(
        "other-linear-wizard/",
        views.OtherLinearWizardViewSet.as_view(),
        name="other-linear-wizard",
    ),
    path(
        "other-linear-wizard/<uuid:run_id>/",
        views.OtherLinearWizardViewSet.as_view(),
        name="other-linear-wizard-run",
    ),
    path(
        "recreated-linear-wizard/",
        views.RecreatedLinearWizardViewSet.as_view(),
        name="recreated-linear-wizard",
    ),
    path(
        "recreated-linear-wizard/<uuid:run_id>/",
        views.RecreatedLinearWizardViewSet.as_view(),
        name="recreated-linear-wizard-run",
    ),
    path(
        "branching-wizard/",
        views.BranchingWizardViewSet.as_view(),
        name="branching-wizard",
    ),
    path(
        "branching-wizard/<uuid:run_id>/",
        views.BranchingWizardViewSet.as_view(),
        name="branching-wizard-run",
    ),
    path(
        "invalid-wizard/",
        views.InvalidWizardViewSet.as_view(),
        name="invalid-wizard",
    ),
]
