from django.urls import path

from . import views


urlpatterns = [
    path(
        "",
        views.IndexView.as_view(),
        name="index",
    ),
    path(
        "wizard/",
        views.SingleStepWizardViewSet.as_view(),
        name="single-step-wizard",
    ),
    path(
        "wizard/<uuid:run_id>/",
        views.SingleStepWizardViewSet.as_view(),
        name="single-step-wizard-run",
    ),
    path(
        "wizard-without-done/",
        views.SingleStepWizardWithoutDoneViewSet.as_view(),
        name="single-step-wizard-without-done",
    ),
    path(
        "wizard-without-done/<uuid:run_id>/",
        views.SingleStepWizardWithoutDoneViewSet.as_view(),
        name="single-step-wizard-without-done-run",
    ),
    path(
        "wizard-done-data/",
        views.SingleStepWizardDoneDataViewSet.as_view(),
        name="single-step-wizard-done-data",
    ),
    path(
        "wizard-done-data/<uuid:run_id>/",
        views.SingleStepWizardDoneDataViewSet.as_view(),
        name="single-step-wizard-done-data-run",
    ),
    path(
        "wizard-done-run-data/",
        views.SingleStepWizardDoneRunDataViewSet.as_view(),
        name="single-step-wizard-done-run-data",
    ),
    path(
        "wizard-done-run-data/<uuid:run_id>/",
        views.SingleStepWizardDoneRunDataViewSet.as_view(),
        name="single-step-wizard-done-run-data-run",
    ),
    path(
        "linear-wizard/",
        views.LinearWizardViewSet.as_view(),
        name="linear-wizard",
    ),
    path(
        "linear-wizard/<uuid:run_id>/",
        views.LinearWizardViewSet.as_view(),
        name="linear-wizard-run",
    ),
    path(
        "done-linear-wizard/",
        views.DoneLinearWizardViewSet.as_view(),
        name="done-linear-wizard",
    ),
    path(
        "done-linear-wizard/<uuid:run_id>/",
        views.DoneLinearWizardViewSet.as_view(),
        name="done-linear-wizard-run",
    ),
    path(
        "other-linear-wizard/",
        views.OtherLinearWizardViewSet.as_view(),
        name="other-linear-wizard",
    ),
    path(
        "other-linear-wizard/<uuid:run_id>/",
        views.OtherLinearWizardViewSet.as_view(),
        name="other-linear-wizard-run",
    ),
    path(
        "recreated-linear-wizard/",
        views.RecreatedLinearWizardViewSet.as_view(),
        name="recreated-linear-wizard",
    ),
    path(
        "recreated-linear-wizard/<uuid:run_id>/",
        views.RecreatedLinearWizardViewSet.as_view(),
        name="recreated-linear-wizard-run",
    ),
    path(
        "branching-wizard/",
        views.BranchingWizardViewSet.as_view(),
        name="branching-wizard",
    ),
    path(
        "branching-wizard/<uuid:run_id>/",
        views.BranchingWizardViewSet.as_view(),
        name="branching-wizard-run",
    ),
    path(
        "editing-branching-wizard/",
        views.EditingBranchingWizardViewSet.as_view(),
        name="editing-branching-wizard",
    ),
    path(
        "editing-branching-wizard/<uuid:run_id>/",
        views.EditingBranchingWizardViewSet.as_view(),
        name="editing-branching-wizard-run",
    ),
    path(
        "done-branching-wizard/",
        views.DoneBranchingWizardViewSet.as_view(),
        name="done-branching-wizard",
    ),
    path(
        "done-branching-wizard/<uuid:run_id>/",
        views.DoneBranchingWizardViewSet.as_view(),
        name="done-branching-wizard-run",
    ),
    path(
        "branch-entry-wizard/",
        views.BranchEntryWizardViewSet.as_view(),
        name="branch-entry-wizard",
    ),
    path(
        "branch-entry-wizard/<uuid:run_id>/",
        views.BranchEntryWizardViewSet.as_view(),
        name="branch-entry-wizard-run",
    ),
    path(
        "duplicate-context-wizard/",
        views.DuplicateContextWizardViewSet.as_view(),
        name="duplicate-context-wizard",
    ),
    path(
        "duplicate-context-wizard/<uuid:run_id>/",
        views.DuplicateContextWizardViewSet.as_view(),
        name="duplicate-context-wizard-run",
    ),
    path(
        "invalid-wizard/",
        views.InvalidWizardViewSet.as_view(),
        name="invalid-wizard",
    ),
    path(
        "form-view-step-wizard/",
        views.FormViewStepWizardViewSet.as_view(),
        name="form-view-step-wizard",
    ),
    path(
        "form-view-step-wizard/<uuid:run_id>/",
        views.FormViewStepWizardViewSet.as_view(),
        name="form-view-step-wizard-run",
    ),
    path(
        "missing-template-wizard/",
        views.MissingTemplateWizardViewSet.as_view(),
        name="missing-template-wizard",
    ),
    path(
        "missing-template-wizard/<uuid:run_id>/",
        views.MissingTemplateWizardViewSet.as_view(),
        name="missing-template-wizard-run",
    ),
    path(
        "pre-configured-wizard/",
        views.PreConfiguredWizardViewSet.as_view(),
        name="pre-configured-wizard",
    ),
    path(
        "pre-configured-wizard/<uuid:run_id>/",
        views.PreConfiguredWizardViewSet.as_view(),
        name="pre-configured-wizard-run",
    ),
    path(
        "empty-wizard/",
        views.EmptyWizardViewSet.as_view(),
        name="empty-wizard",
    ),
    path(
        "empty-wizard/<uuid:run_id>/",
        views.EmptyWizardViewSet.as_view(),
        name="empty-wizard-run",
    ),
    path(
        "double-configured-wizard/",
        views.DoubleConfiguredWizardViewSet.as_view(),
        name="double-configured-wizard",
    ),
    path(
        "double-configured-wizard/<uuid:run_id>/",
        views.DoubleConfiguredWizardViewSet.as_view(),
        name="double-configured-wizard-run",
    ),
    path(
        "merged-payload-wizard/",
        views.MergedPayloadLinearWizardViewSet.as_view(),
        name="merged-payload-wizard",
    ),
    path(
        "merged-payload-wizard/<uuid:run_id>/",
        views.MergedPayloadLinearWizardViewSet.as_view(),
        name="merged-payload-wizard-run",
    ),
    path(
        "path-aware-linear-wizard/",
        views.PathAwareLinearWizardViewSet.as_view(),
        name="path-aware-linear-wizard",
    ),
    path(
        "path-aware-linear-wizard/<uuid:run_id>/",
        views.PathAwareLinearWizardViewSet.as_view(),
        name="path-aware-linear-wizard-run",
    ),
    path(
        "branching-merged-payload-wizard/",
        views.BranchingMergedPayloadWizardViewSet.as_view(),
        name="branching-merged-payload-wizard",
    ),
    path(
        "branching-merged-payload-wizard/<uuid:run_id>/",
        views.BranchingMergedPayloadWizardViewSet.as_view(),
        name="branching-merged-payload-wizard-run",
    ),
    path(
        "empty-branch-arm-merged-payload-wizard/",
        views.EmptyBranchArmMergedPayloadWizardViewSet.as_view(),
        name="empty-branch-arm-merged-payload-wizard",
    ),
    path(
        "empty-branch-arm-merged-payload-wizard/<uuid:run_id>/",
        views.EmptyBranchArmMergedPayloadWizardViewSet.as_view(),
        name="empty-branch-arm-merged-payload-wizard-run",
    ),
    path(
        "runtime-tree-branching-merge-wizard/",
        views.RuntimeTreeBranchingMergeViewSet.as_view(),
        name="runtime-tree-branching-merge-wizard",
    ),
    path(
        "runtime-tree-branching-merge-wizard/<uuid:run_id>/",
        views.RuntimeTreeBranchingMergeViewSet.as_view(),
        name="runtime-tree-branching-merge-wizard-run",
    ),
    path(
        "form-view-step-not-implemented/",
        views.FormViewStepRaisesNotImplementedViewSet.as_view(),
        name="form-view-step-not-implemented",
    ),
    path(
        "form-view-step-not-implemented/<uuid:run_id>/",
        views.FormViewStepRaisesNotImplementedViewSet.as_view(),
        name="form-view-step-not-implemented-run",
    ),
    path(
        "dynamic-wizard/",
        views.DynamicWizardViewSet.as_view(),
        name="dynamic-wizard",
    ),
    path(
        "dynamic-wizard/<uuid:run_id>/",
        views.DynamicWizardViewSet.as_view(),
        name="dynamic-wizard-run",
    ),
    path(
        "dynamic-list-payload-wizard/",
        views.DynamicListPayloadWizardViewSet.as_view(),
        name="dynamic-list-payload-wizard",
    ),
    path(
        "dynamic-list-payload-wizard/<uuid:run_id>/",
        views.DynamicListPayloadWizardViewSet.as_view(),
        name="dynamic-list-payload-wizard-run",
    ),
]
