# Generated by Django 4.2.28 on 2026-08-05 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WizardRun",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("state", models.JSONField(default=list)),
                ("completed", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wizard_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SectionRecord",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=100)),
                ("stash", models.JSONField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wizard_sections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="testapp.wizardrun",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="wizardrun",
            index=models.Index(
                fields=["owner", "updated_at"], name="testapp_wiz_owner_i_c6df1c_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="sectionrecord",
            constraint=models.UniqueConstraint(
                fields=("owner", "key"), name="unique_section"
            ),
        ),
    ]
