# Generated by Django 4.2.28 on 2026-08-15 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("testapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CollectionRecord",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=100)),
                ("declared_done", models.BooleanField(default=False)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wizard_collections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CollectionItemRecord",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("collection_key", models.CharField(max_length=100)),
                ("item_id", models.CharField(max_length=64)),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("position", models.PositiveIntegerField()),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wizard_collection_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
            },
        ),
        migrations.AddConstraint(
            model_name="collectionrecord",
            constraint=models.UniqueConstraint(
                fields=("owner", "key"), name="unique_collection"
            ),
        ),
        migrations.AddConstraint(
            model_name="collectionitemrecord",
            constraint=models.UniqueConstraint(
                fields=("owner", "collection_key", "item_id"),
                name="unique_collection_item",
            ),
        ),
    ]
