# Generated by Django 4.2.28 on 2026-08-27 11:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testapp", "0002_collectionrecord_collectionitemrecord_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="wizardrun",
            name="meta",
            field=models.JSONField(default=dict),
        ),
    ]
