# Generated by Django 4.2.28 on 2026-08-28 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("testapp", "0003_wizardrun_meta"),
    ]

    operations = [
        migrations.CreateModel(
            name="JourneyRecord",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("journey", models.CharField(max_length=100)),
                ("data", models.JSONField(default=dict)),
                ("completed", models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="collectionitemrecord",
            name="unique_collection_item",
        ),
        migrations.RemoveConstraint(
            model_name="collectionrecord",
            name="unique_collection",
        ),
        migrations.RemoveConstraint(
            model_name="sectionrecord",
            name="unique_section",
        ),
        migrations.AddField(
            model_name="collectionitemrecord",
            name="journey",
            field=models.CharField(default="default", max_length=100),
        ),
        migrations.AddField(
            model_name="collectionrecord",
            name="journey",
            field=models.CharField(default="default", max_length=100),
        ),
        migrations.AddField(
            model_name="sectionrecord",
            name="journey",
            field=models.CharField(default="default", max_length=100),
        ),
        migrations.AddConstraint(
            model_name="collectionitemrecord",
            constraint=models.UniqueConstraint(
                fields=("owner", "journey", "collection_key", "item_id"),
                name="unique_collection_item",
            ),
        ),
        migrations.AddConstraint(
            model_name="collectionrecord",
            constraint=models.UniqueConstraint(
                fields=("owner", "journey", "key"), name="unique_collection"
            ),
        ),
        migrations.AddConstraint(
            model_name="sectionrecord",
            constraint=models.UniqueConstraint(
                fields=("owner", "journey", "key"), name="unique_section"
            ),
        ),
        migrations.AddField(
            model_name="journeyrecord",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wizard_journeys",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="journeyrecord",
            constraint=models.UniqueConstraint(
                fields=("owner", "journey"), name="unique_journey"
            ),
        ),
    ]
