# Generated by Django 4.2.28 on 2026-08-28 12:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testapp", "0004_journey"),
    ]

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference", models.CharField(max_length=16, unique=True)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("submitted", models.BooleanField(default=False)),
            ],
        ),
    ]
